// Generated by gencpp from file fiducial_slam/AddFiducial.msg
// DO NOT EDIT!


#ifndef FIDUCIAL_SLAM_MESSAGE_ADDFIDUCIAL_H
#define FIDUCIAL_SLAM_MESSAGE_ADDFIDUCIAL_H

#include <ros/service_traits.h>


#include <fiducial_slam/AddFiducialRequest.h>
#include <fiducial_slam/AddFiducialResponse.h>


namespace fiducial_slam
{

struct AddFiducial
{

typedef AddFiducialRequest Request;
typedef AddFiducialResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddFiducial
} // namespace fiducial_slam


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fiducial_slam::AddFiducial > {
  static const char* value()
  {
    return "d6e0c5dec9dcac4f00b77e79be09ed60";
  }

  static const char* value(const ::fiducial_slam::AddFiducial&) { return value(); }
};

template<>
struct DataType< ::fiducial_slam::AddFiducial > {
  static const char* value()
  {
    return "fiducial_slam/AddFiducial";
  }

  static const char* value(const ::fiducial_slam::AddFiducial&) { return value(); }
};


// service_traits::MD5Sum< ::fiducial_slam::AddFiducialRequest> should match 
// service_traits::MD5Sum< ::fiducial_slam::AddFiducial > 
template<>
struct MD5Sum< ::fiducial_slam::AddFiducialRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fiducial_slam::AddFiducial >::value();
  }
  static const char* value(const ::fiducial_slam::AddFiducialRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fiducial_slam::AddFiducialRequest> should match 
// service_traits::DataType< ::fiducial_slam::AddFiducial > 
template<>
struct DataType< ::fiducial_slam::AddFiducialRequest>
{
  static const char* value()
  {
    return DataType< ::fiducial_slam::AddFiducial >::value();
  }
  static const char* value(const ::fiducial_slam::AddFiducialRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fiducial_slam::AddFiducialResponse> should match 
// service_traits::MD5Sum< ::fiducial_slam::AddFiducial > 
template<>
struct MD5Sum< ::fiducial_slam::AddFiducialResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fiducial_slam::AddFiducial >::value();
  }
  static const char* value(const ::fiducial_slam::AddFiducialResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fiducial_slam::AddFiducialResponse> should match 
// service_traits::DataType< ::fiducial_slam::AddFiducial > 
template<>
struct DataType< ::fiducial_slam::AddFiducialResponse>
{
  static const char* value()
  {
    return DataType< ::fiducial_slam::AddFiducial >::value();
  }
  static const char* value(const ::fiducial_slam::AddFiducialResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FIDUCIAL_SLAM_MESSAGE_ADDFIDUCIAL_H
