// Generated by gencpp from file fiducial_msgs/InitializeMapResponse.msg
// DO NOT EDIT!


#ifndef FIDUCIAL_MSGS_MESSAGE_INITIALIZEMAPRESPONSE_H
#define FIDUCIAL_MSGS_MESSAGE_INITIALIZEMAPRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fiducial_msgs
{
template <class ContainerAllocator>
struct InitializeMapResponse_
{
  typedef InitializeMapResponse_<ContainerAllocator> Type;

  InitializeMapResponse_()
    {
    }
  InitializeMapResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::fiducial_msgs::InitializeMapResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fiducial_msgs::InitializeMapResponse_<ContainerAllocator> const> ConstPtr;

}; // struct InitializeMapResponse_

typedef ::fiducial_msgs::InitializeMapResponse_<std::allocator<void> > InitializeMapResponse;

typedef boost::shared_ptr< ::fiducial_msgs::InitializeMapResponse > InitializeMapResponsePtr;
typedef boost::shared_ptr< ::fiducial_msgs::InitializeMapResponse const> InitializeMapResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fiducial_msgs::InitializeMapResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fiducial_msgs::InitializeMapResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace fiducial_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'fiducial_msgs': ['/home/studi/catkin_ws/src/fiducial_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::fiducial_msgs::InitializeMapResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fiducial_msgs::InitializeMapResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fiducial_msgs::InitializeMapResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fiducial_msgs::InitializeMapResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fiducial_msgs::InitializeMapResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fiducial_msgs::InitializeMapResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fiducial_msgs::InitializeMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::fiducial_msgs::InitializeMapResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::fiducial_msgs::InitializeMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fiducial_msgs/InitializeMapResponse";
  }

  static const char* value(const ::fiducial_msgs::InitializeMapResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fiducial_msgs::InitializeMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::fiducial_msgs::InitializeMapResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fiducial_msgs::InitializeMapResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InitializeMapResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fiducial_msgs::InitializeMapResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::fiducial_msgs::InitializeMapResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // FIDUCIAL_MSGS_MESSAGE_INITIALIZEMAPRESPONSE_H
