// Auto-generated. Do not edit!

// (in-package ur_dashboard_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class SetModeFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.current_robot_mode = null;
      this.current_safety_mode = null;
    }
    else {
      if (initObj.hasOwnProperty('current_robot_mode')) {
        this.current_robot_mode = initObj.current_robot_mode
      }
      else {
        this.current_robot_mode = 0;
      }
      if (initObj.hasOwnProperty('current_safety_mode')) {
        this.current_safety_mode = initObj.current_safety_mode
      }
      else {
        this.current_safety_mode = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type SetModeFeedback
    // Serialize message field [current_robot_mode]
    bufferOffset = _serializer.int8(obj.current_robot_mode, buffer, bufferOffset);
    // Serialize message field [current_safety_mode]
    bufferOffset = _serializer.int8(obj.current_safety_mode, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type SetModeFeedback
    let len;
    let data = new SetModeFeedback(null);
    // Deserialize message field [current_robot_mode]
    data.current_robot_mode = _deserializer.int8(buffer, bufferOffset);
    // Deserialize message field [current_safety_mode]
    data.current_safety_mode = _deserializer.int8(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 2;
  }

  static datatype() {
    // Returns string type for a message object
    return 'ur_dashboard_msgs/SetModeFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'd48caaba06f88e6be0ba90bf29940534';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # feedback
    int8 current_robot_mode
    int8 current_safety_mode
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new SetModeFeedback(null);
    if (msg.current_robot_mode !== undefined) {
      resolved.current_robot_mode = msg.current_robot_mode;
    }
    else {
      resolved.current_robot_mode = 0
    }

    if (msg.current_safety_mode !== undefined) {
      resolved.current_safety_mode = msg.current_safety_mode;
    }
    else {
      resolved.current_safety_mode = 0
    }

    return resolved;
    }
};

module.exports = SetModeFeedback;
