(cl:defpackage ur_dashboard_msgs-msg
  (:use )
  (:export
   "<PROGRAMSTATE>"
   "PROGRAMSTATE"
   "<ROBOTMODE>"
   "ROBOTMODE"
   "<SAFETYMODE>"
   "SAFETYMODE"
   "<SETMODEACTION>"
   "SETMODEACTION"
   "<SETMODEACTIONFEEDBACK>"
   "SETMODEACTIONFEEDBACK"
   "<SETMODEACTIONGOAL>"
   "SETMODEACTIONGOAL"
   "<SETMODEACTIONRESULT>"
   "SETMODEACTIONRESULT"
   "<SETMODEFEEDBACK>"
   "SETMODEFEEDBACK"
   "<SETMODEGOAL>"
   "SETMODEGOAL"
   "<SETMODERESULT>"
   "SETMODERESULT"
  ))

