set(_CATKIN_CURRENT_PACKAGE "fiducial_slam")
set(fiducial_slam_VERSION "0.11.0")
set(fiducial_slam_MAINTAINER "Jim Vaughan <jimv@mrjim.com>, Rohan Agrawal <send2arohan@gmail.com>")
set(fiducial_slam_PACKAGE_FORMAT "2")
set(fiducial_slam_BUILD_DEPENDS "roscpp" "tf2_geometry_msgs" "tf2_ros" "tf2" "visualization_msgs" "image_transport" "sensor_msgs" "cv_bridge" "fiducial_msgs" "dynamic_reconfigure")
set(fiducial_slam_BUILD_EXPORT_DEPENDS "roscpp" "tf2_geometry_msgs" "tf2_ros" "tf2" "visualization_msgs" "image_transport" "sensor_msgs" "cv_bridge" "fiducial_msgs" "dynamic_reconfigure")
set(fiducial_slam_BUILDTOOL_DEPENDS "catkin")
set(fiducial_slam_BUILDTOOL_EXPORT_DEPENDS )
set(fiducial_slam_EXEC_DEPENDS "roscpp" "tf2_geometry_msgs" "tf2_ros" "tf2" "visualization_msgs" "image_transport" "sensor_msgs" "cv_bridge" "fiducial_msgs" "dynamic_reconfigure")
set(fiducial_slam_RUN_DEPENDS "roscpp" "tf2_geometry_msgs" "tf2_ros" "tf2" "visualization_msgs" "image_transport" "sensor_msgs" "cv_bridge" "fiducial_msgs" "dynamic_reconfigure")
set(fiducial_slam_TEST_DEPENDS )
set(fiducial_slam_DOC_DEPENDS )
set(fiducial_slam_URL_WEBSITE "")
set(fiducial_slam_URL_BUGTRACKER "")
set(fiducial_slam_URL_REPOSITORY "")
set(fiducial_slam_DEPRECATED "")