# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from fiducial_msgs/Fiducial.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Fiducial(genpy.Message):
  _md5sum = "a0094064db6c7772c6b638a2dab17f42"
  _type = "fiducial_msgs/Fiducial"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """ # Details of a detected fiducial.

 int32 fiducial_id
 int32 direction

 # vertices
 float64 x0
 float64 y0
 float64 x1
 float64 y1
 float64 x2
 float64 y2
 float64 x3
 float64 y3
"""
  __slots__ = ['fiducial_id','direction','x0','y0','x1','y1','x2','y2','x3','y3']
  _slot_types = ['int32','int32','float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       fiducial_id,direction,x0,y0,x1,y1,x2,y2,x3,y3

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Fiducial, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.fiducial_id is None:
        self.fiducial_id = 0
      if self.direction is None:
        self.direction = 0
      if self.x0 is None:
        self.x0 = 0.
      if self.y0 is None:
        self.y0 = 0.
      if self.x1 is None:
        self.x1 = 0.
      if self.y1 is None:
        self.y1 = 0.
      if self.x2 is None:
        self.x2 = 0.
      if self.y2 is None:
        self.y2 = 0.
      if self.x3 is None:
        self.x3 = 0.
      if self.y3 is None:
        self.y3 = 0.
    else:
      self.fiducial_id = 0
      self.direction = 0
      self.x0 = 0.
      self.y0 = 0.
      self.x1 = 0.
      self.y1 = 0.
      self.x2 = 0.
      self.y2 = 0.
      self.x3 = 0.
      self.y3 = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2i8d().pack(_x.fiducial_id, _x.direction, _x.x0, _x.y0, _x.x1, _x.y1, _x.x2, _x.y2, _x.x3, _x.y3))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 72
      (_x.fiducial_id, _x.direction, _x.x0, _x.y0, _x.x1, _x.y1, _x.x2, _x.y2, _x.x3, _x.y3,) = _get_struct_2i8d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2i8d().pack(_x.fiducial_id, _x.direction, _x.x0, _x.y0, _x.x1, _x.y1, _x.x2, _x.y2, _x.x3, _x.y3))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 72
      (_x.fiducial_id, _x.direction, _x.x0, _x.y0, _x.x1, _x.y1, _x.x2, _x.y2, _x.x3, _x.y3,) = _get_struct_2i8d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2i8d = None
def _get_struct_2i8d():
    global _struct_2i8d
    if _struct_2i8d is None:
        _struct_2i8d = struct.Struct("<2i8d")
    return _struct_2i8d
