set(_CATKIN_CURRENT_PACKAGE "aruco_detect")
set(aruco_detect_VERSION "0.11.0")
set(aruco_detect_MAINTAINER "Jim Vaughan <jimv@mrjim.com>, Rohan Agrawal <send2arohan@gmail.com>")
set(aruco_detect_PACKAGE_FORMAT "2")
set(aruco_detect_BUILD_DEPENDS "roscpp" "tf2_geometry_msgs" "tf2_ros" "tf2" "visualization_msgs" "image_transport" "sensor_msgs" "cv_bridge" "fiducial_msgs" "dynamic_reconfigure" "python-cairosvg" "python-joblib")
set(aruco_detect_BUILD_EXPORT_DEPENDS "roscpp" "tf2_geometry_msgs" "tf2_ros" "tf2" "visualization_msgs" "image_transport" "sensor_msgs" "cv_bridge" "fiducial_msgs" "dynamic_reconfigure" "python-cairosvg" "python-joblib")
set(aruco_detect_BUILDTOOL_DEPENDS "catkin")
set(aruco_detect_BUILDTOOL_EXPORT_DEPENDS )
set(aruco_detect_EXEC_DEPENDS "roscpp" "tf2_geometry_msgs" "tf2_ros" "tf2" "visualization_msgs" "image_transport" "sensor_msgs" "cv_bridge" "fiducial_msgs" "dynamic_reconfigure" "python-cairosvg" "python-joblib")
set(aruco_detect_RUN_DEPENDS "roscpp" "tf2_geometry_msgs" "tf2_ros" "tf2" "visualization_msgs" "image_transport" "sensor_msgs" "cv_bridge" "fiducial_msgs" "dynamic_reconfigure" "python-cairosvg" "python-joblib")
set(aruco_detect_TEST_DEPENDS )
set(aruco_detect_DOC_DEPENDS )
set(aruco_detect_URL_WEBSITE "")
set(aruco_detect_URL_BUGTRACKER "")
set(aruco_detect_URL_REPOSITORY "")
set(aruco_detect_DEPRECATED "")