set(_CATKIN_CURRENT_PACKAGE "fiducials")
set(fiducials_VERSION "0.11.0")
set(fiducials_MAINTAINER "Jim Vaughan <jimv@mrjim.com>, Rohan Agrawal <send2arohan@gmail.com>")
set(fiducials_PACKAGE_FORMAT "2")
set(fiducials_BUILD_DEPENDS )
set(fiducials_BUILD_EXPORT_DEPENDS )
set(fiducials_BUILDTOOL_DEPENDS "catkin")
set(fiducials_BUILDTOOL_EXPORT_DEPENDS )
set(fiducials_EXEC_DEPENDS "aruco_detect" "fiducial_slam" "fiducial_msgs")
set(fiducials_RUN_DEPENDS "aruco_detect" "fiducial_slam" "fiducial_msgs")
set(fiducials_TEST_DEPENDS )
set(fiducials_DOC_DEPENDS )
set(fiducials_URL_WEBSITE "http://wiki.ros.org/fiducials")
set(fiducials_URL_BUGTRACKER "")
set(fiducials_URL_REPOSITORY "")
set(fiducials_DEPRECATED "")