// Generated by gencpp from file ur_dashboard_msgs/AddToLog.msg
// DO NOT EDIT!


#ifndef UR_DASHBOARD_MSGS_MESSAGE_ADDTOLOG_H
#define UR_DASHBOARD_MSGS_MESSAGE_ADDTOLOG_H

#include <ros/service_traits.h>


#include <ur_dashboard_msgs/AddToLogRequest.h>
#include <ur_dashboard_msgs/AddToLogResponse.h>


namespace ur_dashboard_msgs
{

struct AddToLog
{

typedef AddToLogRequest Request;
typedef AddToLogResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddToLog
} // namespace ur_dashboard_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ur_dashboard_msgs::AddToLog > {
  static const char* value()
  {
    return "2054bf354d51f4d6a4dce330cf7bb805";
  }

  static const char* value(const ::ur_dashboard_msgs::AddToLog&) { return value(); }
};

template<>
struct DataType< ::ur_dashboard_msgs::AddToLog > {
  static const char* value()
  {
    return "ur_dashboard_msgs/AddToLog";
  }

  static const char* value(const ::ur_dashboard_msgs::AddToLog&) { return value(); }
};


// service_traits::MD5Sum< ::ur_dashboard_msgs::AddToLogRequest> should match 
// service_traits::MD5Sum< ::ur_dashboard_msgs::AddToLog > 
template<>
struct MD5Sum< ::ur_dashboard_msgs::AddToLogRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ur_dashboard_msgs::AddToLog >::value();
  }
  static const char* value(const ::ur_dashboard_msgs::AddToLogRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur_dashboard_msgs::AddToLogRequest> should match 
// service_traits::DataType< ::ur_dashboard_msgs::AddToLog > 
template<>
struct DataType< ::ur_dashboard_msgs::AddToLogRequest>
{
  static const char* value()
  {
    return DataType< ::ur_dashboard_msgs::AddToLog >::value();
  }
  static const char* value(const ::ur_dashboard_msgs::AddToLogRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ur_dashboard_msgs::AddToLogResponse> should match 
// service_traits::MD5Sum< ::ur_dashboard_msgs::AddToLog > 
template<>
struct MD5Sum< ::ur_dashboard_msgs::AddToLogResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ur_dashboard_msgs::AddToLog >::value();
  }
  static const char* value(const ::ur_dashboard_msgs::AddToLogResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur_dashboard_msgs::AddToLogResponse> should match 
// service_traits::DataType< ::ur_dashboard_msgs::AddToLog > 
template<>
struct DataType< ::ur_dashboard_msgs::AddToLogResponse>
{
  static const char* value()
  {
    return DataType< ::ur_dashboard_msgs::AddToLog >::value();
  }
  static const char* value(const ::ur_dashboard_msgs::AddToLogResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UR_DASHBOARD_MSGS_MESSAGE_ADDTOLOG_H
