// Generated by gencpp from file ur_dashboard_msgs/Load.msg
// DO NOT EDIT!


#ifndef UR_DASHBOARD_MSGS_MESSAGE_LOAD_H
#define UR_DASHBOARD_MSGS_MESSAGE_LOAD_H

#include <ros/service_traits.h>


#include <ur_dashboard_msgs/LoadRequest.h>
#include <ur_dashboard_msgs/LoadResponse.h>


namespace ur_dashboard_msgs
{

struct Load
{

typedef LoadRequest Request;
typedef LoadResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Load
} // namespace ur_dashboard_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ur_dashboard_msgs::Load > {
  static const char* value()
  {
    return "abbee7d5c683c0b3af261ba331da1fbb";
  }

  static const char* value(const ::ur_dashboard_msgs::Load&) { return value(); }
};

template<>
struct DataType< ::ur_dashboard_msgs::Load > {
  static const char* value()
  {
    return "ur_dashboard_msgs/Load";
  }

  static const char* value(const ::ur_dashboard_msgs::Load&) { return value(); }
};


// service_traits::MD5Sum< ::ur_dashboard_msgs::LoadRequest> should match 
// service_traits::MD5Sum< ::ur_dashboard_msgs::Load > 
template<>
struct MD5Sum< ::ur_dashboard_msgs::LoadRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ur_dashboard_msgs::Load >::value();
  }
  static const char* value(const ::ur_dashboard_msgs::LoadRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur_dashboard_msgs::LoadRequest> should match 
// service_traits::DataType< ::ur_dashboard_msgs::Load > 
template<>
struct DataType< ::ur_dashboard_msgs::LoadRequest>
{
  static const char* value()
  {
    return DataType< ::ur_dashboard_msgs::Load >::value();
  }
  static const char* value(const ::ur_dashboard_msgs::LoadRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ur_dashboard_msgs::LoadResponse> should match 
// service_traits::MD5Sum< ::ur_dashboard_msgs::Load > 
template<>
struct MD5Sum< ::ur_dashboard_msgs::LoadResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ur_dashboard_msgs::Load >::value();
  }
  static const char* value(const ::ur_dashboard_msgs::LoadResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur_dashboard_msgs::LoadResponse> should match 
// service_traits::DataType< ::ur_dashboard_msgs::Load > 
template<>
struct DataType< ::ur_dashboard_msgs::LoadResponse>
{
  static const char* value()
  {
    return DataType< ::ur_dashboard_msgs::Load >::value();
  }
  static const char* value(const ::ur_dashboard_msgs::LoadResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UR_DASHBOARD_MSGS_MESSAGE_LOAD_H
