// Generated by gencpp from file ur_dashboard_msgs/Popup.msg
// DO NOT EDIT!


#ifndef UR_DASHBOARD_MSGS_MESSAGE_POPUP_H
#define UR_DASHBOARD_MSGS_MESSAGE_POPUP_H

#include <ros/service_traits.h>


#include <ur_dashboard_msgs/PopupRequest.h>
#include <ur_dashboard_msgs/PopupResponse.h>


namespace ur_dashboard_msgs
{

struct Popup
{

typedef PopupRequest Request;
typedef PopupResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Popup
} // namespace ur_dashboard_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ur_dashboard_msgs::Popup > {
  static const char* value()
  {
    return "2054bf354d51f4d6a4dce330cf7bb805";
  }

  static const char* value(const ::ur_dashboard_msgs::Popup&) { return value(); }
};

template<>
struct DataType< ::ur_dashboard_msgs::Popup > {
  static const char* value()
  {
    return "ur_dashboard_msgs/Popup";
  }

  static const char* value(const ::ur_dashboard_msgs::Popup&) { return value(); }
};


// service_traits::MD5Sum< ::ur_dashboard_msgs::PopupRequest> should match 
// service_traits::MD5Sum< ::ur_dashboard_msgs::Popup > 
template<>
struct MD5Sum< ::ur_dashboard_msgs::PopupRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ur_dashboard_msgs::Popup >::value();
  }
  static const char* value(const ::ur_dashboard_msgs::PopupRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur_dashboard_msgs::PopupRequest> should match 
// service_traits::DataType< ::ur_dashboard_msgs::Popup > 
template<>
struct DataType< ::ur_dashboard_msgs::PopupRequest>
{
  static const char* value()
  {
    return DataType< ::ur_dashboard_msgs::Popup >::value();
  }
  static const char* value(const ::ur_dashboard_msgs::PopupRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ur_dashboard_msgs::PopupResponse> should match 
// service_traits::MD5Sum< ::ur_dashboard_msgs::Popup > 
template<>
struct MD5Sum< ::ur_dashboard_msgs::PopupResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ur_dashboard_msgs::Popup >::value();
  }
  static const char* value(const ::ur_dashboard_msgs::PopupResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur_dashboard_msgs::PopupResponse> should match 
// service_traits::DataType< ::ur_dashboard_msgs::Popup > 
template<>
struct DataType< ::ur_dashboard_msgs::PopupResponse>
{
  static const char* value()
  {
    return DataType< ::ur_dashboard_msgs::Popup >::value();
  }
  static const char* value(const ::ur_dashboard_msgs::PopupResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UR_DASHBOARD_MSGS_MESSAGE_POPUP_H
