# CMake generated Testfile for 
# Source directory: /home/studi/catkin_ws/src/fiducial_slam
# Build directory: /home/studi/catkin_ws/src/fiducial_slam
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_fiducial_slam_gtest_transform_var_test "/home/studi/catkin_ws/src/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/studi/catkin_ws/src/test_results/fiducial_slam/gtest-transform_var_test.xml" "--return-code" "/home/studi/catkin_ws/src/devel/lib/fiducial_slam/transform_var_test --gtest_output=xml:/home/studi/catkin_ws/src/test_results/fiducial_slam/gtest-transform_var_test.xml")
add_test(_ctest_fiducial_slam_rostest_test_create_map_aruco.xml "/home/studi/catkin_ws/src/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/studi/catkin_ws/src/test_results/fiducial_slam/rostest-test_create_map_aruco.xml" "--return-code" "/opt/ros/melodic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/studi/catkin_ws/src/fiducial_slam --package=fiducial_slam --results-filename test_create_map_aruco.xml --results-base-dir \"/home/studi/catkin_ws/src/test_results\" /home/studi/catkin_ws/src/fiducial_slam/test/create_map_aruco.xml ")
add_test(_ctest_fiducial_slam_rostest_test_init_map_aruco.xml "/home/studi/catkin_ws/src/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/studi/catkin_ws/src/test_results/fiducial_slam/rostest-test_init_map_aruco.xml" "--return-code" "/opt/ros/melodic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/studi/catkin_ws/src/fiducial_slam --package=fiducial_slam --results-filename test_init_map_aruco.xml --results-base-dir \"/home/studi/catkin_ws/src/test_results\" /home/studi/catkin_ws/src/fiducial_slam/test/init_map_aruco.xml ")
add_test(_ctest_fiducial_slam_rostest_test_auto_init_403.test "/home/studi/catkin_ws/src/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/studi/catkin_ws/src/test_results/fiducial_slam/rostest-test_auto_init_403.xml" "--return-code" "/opt/ros/melodic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/studi/catkin_ws/src/fiducial_slam --package=fiducial_slam --results-filename test_auto_init_403.xml --results-base-dir \"/home/studi/catkin_ws/src/test_results\" /home/studi/catkin_ws/src/fiducial_slam/test/auto_init_403.test ")
