(cl:in-package ur_msgs-msg)
(cl:export '(TIMESTAMP-VAL
          TIMESTAMP
          IS_ROBOT_CONNECTED-VAL
          IS_ROBOT_CONNECTED
          IS_REAL_ROBOT_ENABLED-VAL
          IS_REAL_ROBOT_ENABLED
          IS_POWER_ON_ROBOT-VAL
          IS_POWER_ON_ROBOT
          IS_EMERGENCY_STOPPED-VAL
          IS_EMERGENCY_STOPPED
          IS_PROTECTIVE_STOPPED-VAL
          IS_PROTECTIVE_STOPPED
          IS_PROGRAM_RUNNING-VAL
          IS_PROGRAM_RUNNING
          IS_PROGRAM_PAUSED-VAL
          IS_PROGRAM_PAUSED
))