(cl:in-package ur_msgs-msg)
(cl:export '(TIME-VAL
          TIME
          Q_TARGET-VAL
          Q_TARGET
          QD_TARGET-VAL
          QD_TARGET
          QDD_TARGET-VAL
          QDD_TARGET
          I_TARGET-VAL
          I_TARGET
          M_TARGET-VAL
          M_TARGET
          Q_ACTUAL-VAL
          Q_ACTUAL
          QD_ACTUAL-VAL
          QD_ACTUAL
          I_ACTUAL-VAL
          I_ACTUAL
          TOOL_ACC_VALUES-VAL
          TOOL_ACC_VALUES
          TCP_FORCE-VAL
          TCP_FORCE
          TOOL_VECTOR-VAL
          TOOL_VECTOR
          TCP_SPEED-VAL
          TCP_SPEED
          DIGITAL_INPUT_BITS-VAL
          DIGITAL_INPUT_BITS
          MOTOR_TEMPERATURES-VAL
          MOTOR_TEMPERATURES
          CONTROLLER_TIMER-VAL
          CONTROLLER_TIMER
          TEST_VALUE-VAL
          TEST_VALUE
          ROBOT_MODE-VAL
          ROBOT_MODE
          JOINT_MODES-VAL
          JOINT_MODES
))