(cl:defpackage fiducial_msgs-msg
  (:use )
  (:export
   "<FIDUCIAL>"
   "FIDUCIAL"
   "<FIDUCIALARRAY>"
   "FIDUCIALARRAY"
   "<FIDUCIALMAPENTRY>"
   "FIDUCIALMAPENTRY"
   "<FIDUCIALMAPENTRYARRAY>"
   "FIDUCIALMAPENTRYARRAY"
   "<FIDUCIALTRANSFORM>"
   "FIDUCIALTRANSFORM"
   "<FIDUCIALTRANSFORMARRAY>"
   "FIDUCIALTRANSFORMARRAY"
  ))

