set(_CATKIN_CURRENT_PACKAGE "fiducial_msgs")
set(fiducial_msgs_VERSION "0.11.0")
set(fiducial_msgs_MAINTAINER "Jim Vaughan <jimv@mrjim.com>, Rohan Agrawal <send2arohan@gmail.com>")
set(fiducial_msgs_PACKAGE_FORMAT "2")
set(fiducial_msgs_BUILD_DEPENDS "message_generation" "geometry_msgs" "sensor_msgs" "std_msgs" "tf")
set(fiducial_msgs_BUILD_EXPORT_DEPENDS "message_runtime" "geometry_msgs" "sensor_msgs" "std_msgs" "tf")
set(fiducial_msgs_BUILDTOOL_DEPENDS "catkin")
set(fiducial_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(fiducial_msgs_EXEC_DEPENDS "message_runtime" "geometry_msgs" "sensor_msgs" "std_msgs" "tf")
set(fiducial_msgs_RUN_DEPENDS "message_runtime" "geometry_msgs" "sensor_msgs" "std_msgs" "tf")
set(fiducial_msgs_TEST_DEPENDS )
set(fiducial_msgs_DOC_DEPENDS )
set(fiducial_msgs_URL_WEBSITE "")
set(fiducial_msgs_URL_BUGTRACKER "")
set(fiducial_msgs_URL_REPOSITORY "")
set(fiducial_msgs_DEPRECATED "")