// Generated by gencpp from file ur_msgs/SetPayload.msg
// DO NOT EDIT!


#ifndef UR_MSGS_MESSAGE_SETPAYLOAD_H
#define UR_MSGS_MESSAGE_SETPAYLOAD_H

#include <ros/service_traits.h>


#include <ur_msgs/SetPayloadRequest.h>
#include <ur_msgs/SetPayloadResponse.h>


namespace ur_msgs
{

struct SetPayload
{

typedef SetPayloadRequest Request;
typedef SetPayloadResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPayload
} // namespace ur_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ur_msgs::SetPayload > {
  static const char* value()
  {
    return "7f12eb632882cb73e5721178d0073e39";
  }

  static const char* value(const ::ur_msgs::SetPayload&) { return value(); }
};

template<>
struct DataType< ::ur_msgs::SetPayload > {
  static const char* value()
  {
    return "ur_msgs/SetPayload";
  }

  static const char* value(const ::ur_msgs::SetPayload&) { return value(); }
};


// service_traits::MD5Sum< ::ur_msgs::SetPayloadRequest> should match 
// service_traits::MD5Sum< ::ur_msgs::SetPayload > 
template<>
struct MD5Sum< ::ur_msgs::SetPayloadRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ur_msgs::SetPayload >::value();
  }
  static const char* value(const ::ur_msgs::SetPayloadRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur_msgs::SetPayloadRequest> should match 
// service_traits::DataType< ::ur_msgs::SetPayload > 
template<>
struct DataType< ::ur_msgs::SetPayloadRequest>
{
  static const char* value()
  {
    return DataType< ::ur_msgs::SetPayload >::value();
  }
  static const char* value(const ::ur_msgs::SetPayloadRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ur_msgs::SetPayloadResponse> should match 
// service_traits::MD5Sum< ::ur_msgs::SetPayload > 
template<>
struct MD5Sum< ::ur_msgs::SetPayloadResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ur_msgs::SetPayload >::value();
  }
  static const char* value(const ::ur_msgs::SetPayloadResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur_msgs::SetPayloadResponse> should match 
// service_traits::DataType< ::ur_msgs::SetPayload > 
template<>
struct DataType< ::ur_msgs::SetPayloadResponse>
{
  static const char* value()
  {
    return DataType< ::ur_msgs::SetPayload >::value();
  }
  static const char* value(const ::ur_msgs::SetPayloadResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UR_MSGS_MESSAGE_SETPAYLOAD_H
