(cl:defpackage ur_msgs-srv
  (:use )
  (:export
   "SETIO"
   "<SETIO-REQUEST>"
   "SETIO-REQUEST"
   "<SETIO-RESPONSE>"
   "SETIO-RESPONSE"
   "SETPAYLOAD"
   "<SETPAYLOAD-REQUEST>"
   "SETPAYLOAD-REQUEST"
   "<SETPAYLOAD-RESPONSE>"
   "SETPAYLOAD-RESPONSE"
   "SETSPEEDSLIDERFRACTION"
   "<SETSPEEDSLIDERFRACTION-REQUEST>"
   "SETSPEEDSLIDERFRACTION-REQUEST"
   "<SETSPEEDSLIDERFRACTION-RESPONSE>"
   "SETSPEEDSLIDERFRACTION-RESPONSE"
  ))

